### ISSUE TITLE
1.17GOGOGO

### ISSUE THREAD

**Issue by BigAppleClass** [xKukiMonster/CreeperConfetti#4]
Support 1.17 thanks

**Comment by askrealcookie** [comment]
Hey! Have you tested it out? Is plugin not working? If API didn't change it should work just fine, let me know so I can look into it! If plugin in is colored red in /plugins or there are any errors in console please give me logs from console.

**Comment by askrealcookie** [comment]
Closing for now, because it seems like plugin works with 1.17. Haven't tested that myself yet tho. May reopen in near future.
