### ISSUE TITLE
Is it compatible with 1.18.2?

### ISSUE THREAD

**Issue by warengonzaga** [xKukiMonster/CreeperConfetti#5]
Just checking if this is compatible with the v1.18.2 version of the Minecraft server.

**Comment by askrealcookie** [comment]
As I can see on the [plugin's bStats page](https://bstats.org/plugin/bukkit/CreeperConfetti/9232#minecraftVersion), almost 40% of servers with CreeperConfetti run on 1.18.2. Make sure to use Spigot or Paper engine(or any of their forks).
Please open a new issue if you have any more questions or if you encounter a problem.
