### ISSUE TITLE
Doesn't work at 1.20.4.

### ISSUE THREAD

**Issue by Trangvn213** [xKukiMonster/CreeperConfetti#6]
I installed the plugin on the server with **geyser** installed, it worked fine on **1.20.50(PE) and 1.20.4(Java)** before, but now it no **longer works**, still creating fireworks ,production rate Creeper fireworks are still 100, there seems to be no change to server settings. If possible, please give me an example of a solution

**Comment by askrealcookie** [comment]
Hi, I'm not familiar with Geyser but I have just checked and the plugin works fine for me on the latest 1.20.4 Spigot with Geyser plugin installed.
![image](https://github.com/askrealcookie/CreeperConfetti/assets/47023698/9b19fccb-371c-4c06-af0a-1e34eb4777fc)

Can you elaborate in what way the plugin no longer works, but at the same time it is still creating fireworks?

**Comment by Trangvn213** [comment]
I don't know anymore, currently my Server is working very well, there are some plugins installed, but almost all plugins are working well, according to my observation, the creeper will explode fireworks and then lose the block .I also don't know why the plugin stopped working, even though it still worked very well before

**Comment by Trangvn213** [comment]
Oh, I'm so sorry. It seems I installed a plugin called 'music', which affected the music disc and creeper. I tried deleting that plugin, as a result, your plugin works as usual.I'm really sorry for bothering you recently
